"""more_coluumns

Revision ID: d4485613ebf8
Revises: 64055e1116e9
Create Date: 2023-12-27 00:00:01.090865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4485613ebf8'
down_revision: Union[str, None] = '64055e1116e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'date_modified')
    op.drop_column('articles', 'date_created')
    op.drop_column('articles', 'published')
    # ### end Alembic commands ###
