version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_new_www
    restart: always
    ports:
      - "7432:5432"
    env_file:
      - ./new_www/.env
    volumes:
      - ./db_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_new_www
    restart: always
    ports:
      - "6051:80"
    env_file:
      - ./new_www/.env
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  app:
    build: .
    container_name: new_www
    restart: always
    ports:
      - "8088:8000"
    env_file:
      - ./new_www/.env
    volumes:
      - ./new_www:/src
    stdin_open: true
    tty: true
